---

- name: A conditional Play Challenge
  hosts: webservers
  gather_facts: no

  vars_prompt:
    name: value
    prompt: Enter yes or no
    private: no
      
  vars:
    epic: true
    distro: Ubuntu

  tasks:
    - name: Validation for prompt
      assert:
        that:
          - value == "yes" or value == "no"
        fail_msg: "Incorrect input"
        quiet: yes
   
    - name: Print if question is true and distro is Ubuntu
      debug:
        msg: "Task 1"
      when: value == 'yes' and distro == 'Ubuntu'
    
    - name: Print if question is false and epic is true
      debug:
        msg: "Task 2"
      when: epic | bool or value == 'no'

 