---

- hosts: webservers
  gather_facts: no
  name: play with prompt

  vars_prompt: 
    - name: my_var
      prompt: "Enter a value or text"
      private: no
      default: Hello, there!
  
  tasks:
  - name: print prompt variable
    debug:
      var: my_var

