---

- name: A play using with items
  hosts: webservers
  gather_facts: no

  vars:
    mylist:
      - One
      - Two


  tasks:
  - name: Printing a list
    debug: 
      msg: "Hello {{ item }}"
    with_items:
      - John
      - Jane
      - Alex
      - Sarah
    when: item == 'Alex' or item == 'John'
    