---

- name: A play with facts
  hosts: webservers
  become: yes
  become_user: root
  
  tasks:

  - name: Install Apache packages
    apt:
      name: apache2
    notify:
      - success_msg_2
      - success_msg
  
  handlers:
    - name: success_msg
      debug: 
        msg: "Package has been installed"
      
    - name: success_msg_2
      debug:
        msg: "This is the second handler"

  
