---
# tasks file for motd-setup



- name: Use REST API to retrieve some data
  uri:
    url: "{{ API_PATH }}"
    return_content: true
    body_format: json
  register: output
  run_once: true
  #delegate_to: local # run this taks on the local machine

- name: Create a var for fact
  set_fact:
    motd_msg: "{{ output.json.fact }}"

- name: Copy motd file to remote server
  template:
    src: "{{ TEMPLATE_PATH }}"
    dest: "{{ DEST_PATH }}"
    owner: root
    group: root
    mode: 0444

#- name: Display retrieved data
#  debug:
#    var: output.json.fact
